In [1]:
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras import layers
from keras.layers import Dense,Flatten,Dropout,Embedding,SimpleRNN,LSTM,SpatialDropout1D
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
import re

In [2]:
data = pd.read_csv("Sentiment.csv") #uploading data

In [3]:
data=data[['text','sentiment']] #execlude all columns except these two columns

In [4]:
data=data[data.sentiment != "Neutral"] #do not take the neutal rate just positve or Negaitve
data['text'] = data['text'].apply(lambda x: x.lower()) #convert all letters to lower case
data['text'] = data['text'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]','',x)) # do not take any charcheter out of the range of ( A - Z or a-z or 0-9)

In [5]:
for idx, row in data.iterrows():  #to remove the rt from the
  row[0]=row[0].replace('rt','')  #to loop on all rows on colloum text

In [13]:
max_features=2000  #to make a tokenization in all sentences and split words in all sentences with spaces
tokenizer = Tokenizer(num_words=max_features, split = ' ') #identifing to the tokenizer that the max words will be only 2000
tokenizer.fit_on_texts(data['text'].values) #to appling the tokenizer on each sentence
x=tokenizer.texts_to_sequences(data['text'].values)
x=pad_sequences(x) #to make all sentencs have the same length so he will increase zeros to small sentences
print(x)


[[   0    0    0 ... 1301 1386  732]
 [   0    0    0 ...  231  712   17]
 [   0    0    0 ...  204  366  678]
 ...
 [   0    0    0 ...   71   65    3]
 [   0    0    0 ... 1004 1398   73]
 [   0    0    0 ...  194    3  710]]


In [7]:
embed_dim = 128 #number of quetsions who the model will ask for mthe sentences in order to give the words a percentage we could use it in recognizing whom are similar
lstm_out=196 #number of nurens of the LSTM model (Nuerons)

model = Sequential() #the box whom will connected all the belopw model layers
model.add(Embedding(max_features,embed_dim,input_length=x.shape[1]))#take the first column max sentance(10729,28)هياخد ال 28 كولوم و ياخد اطول طول جكلة فيهم ده بعدج ما عملنا tocknizier لل text
model.add(SpatialDropout1D(0.4))#used to drop out some of neurons the layer betwen the output of the
model.add(LSTM(lstm_out,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(2,'softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
y = pd.get_dummies(data['sentiment']).values


In [10]:
x.shape

(10729, 28)

In [8]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3, random_state=42)
print(x_train.shape,y_train.shape)

(7510, 28) (7510, 2)


In [9]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
235/235 [==============================] - 62s 226ms/step - loss: 0.4342 - accuracy: 0.8182
Epoch 2/10
235/235 [==============================] - 37s 156ms/step - loss: 0.3214 - accuracy: 0.8676
Epoch 3/10
235/235 [==============================] - 35s 151ms/step - loss: 0.2827 - accuracy: 0.8834
Epoch 4/10
235/235 [==============================] - 34s 146ms/step - loss: 0.2468 - accuracy: 0.9013
Epoch 5/10
235/235 [==============================] - 32s 138ms/step - loss: 0.2197 - accuracy: 0.9121
Epoch 6/10
235/235 [==============================] - 34s 146ms/step - loss: 0.1970 - accuracy: 0.9204
Epoch 7/10
235/235 [==============================] - 34s 145ms/step - loss: 0.1782 - accuracy: 0.9304
Epoch 8/10
235/235 [==============================] - 33s 139ms/step - loss: 0.1644 - accuracy: 0.9340
Epoch 9/10
235/235 [==============================] - 35s 149ms/step - loss: 0.1484 - accuracy: 0.9389
Epoch 10/10
235/235 [==============================] - 33s 143ms/step - l